# Generated by Django 2.1 on 2019-05-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proapartment',
            options={'verbose_name': '户型', 'verbose_name_plural': '户型'},
        ),
        migrations.AlterModelOptions(
            name='probanner',
            options={'verbose_name': '项目轮播图', 'verbose_name_plural': '项目轮播图'},
        ),
        migrations.AlterModelOptions(
            name='provideo',
            options={'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='pro_img',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=32, verbose_name='国家名字'),
        ),
        migrations.AlterField(
            model_name='proapartment',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址(图片第三方链接)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='坐落地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_simple_desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='项目简单介绍'),
        ),
    ]
