# Generated by Django 2.1 on 2019-05-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190512_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='经度'),
        ),
    ]
