# Generated by Django 2.1 on 2019-07-31 17:47

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190524_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='proapartment',
            name='index',
            field=models.IntegerField(default=100, verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='project',
            name='gif_img',
            field=models.ImageField(blank=True, help_text='690*360', max_length=128, null=True, upload_to='project/gif/%Y%m%d', verbose_name='项目gif图片'),
        ),
        migrations.AddField(
            model_name='project',
            name='index',
            field=models.IntegerField(default=10, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='proapartment',
            name='apartment_img',
            field=models.FileField(blank=True, help_text='690*240', max_length=128, null=True, upload_to='project/apartment/%Y%m%d', verbose_name='户型图片'),
        ),
        migrations.AlterField(
            model_name='probanner',
            name='img',
            field=models.ImageField(blank=True, help_text='690*360', max_length=128, null=True, upload_to='project/banner/%Y%m%d', verbose_name='项目轮播图片'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo_img',
            field=models.ImageField(blank=True, help_text='250*100', max_length=128, null=True, upload_to='project/logo/%Y%m%d', verbose_name='项目logo图片'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_description',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='项目详细介绍 '),
        ),
    ]
