# Generated by Django 2.1 on 2019-12-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190731_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='probanner',
            name='index',
            field=models.IntegerField(default=10, verbose_name='顺序'),
        ),
    ]
