# Generated by Django 2.1 on 2019-12-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='活动名称')),
                ('into_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='activity/image/%Y%m%d', verbose_name='入口图片')),
                ('master_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='activity/image/%Y%m%d', verbose_name='活动主图')),
                ('is_on_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Signupsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('contact_info', models.CharField(max_length=32, verbose_name='联系方式')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱地址')),
            ],
            options={
                'verbose_name': '活动报名表',
                'verbose_name_plural': '活动报名表',
            },
        ),
    ]
