# Generated by Django 2.1 on 2019-12-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupsheet',
            name='activity_id',
            field=models.IntegerField(default=1, verbose_name='活动id'),
            preserve_default=False,
        ),
    ]
