# Generated by Django 2.1 on 2019-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('contact_info', models.CharField(max_length=32, verbose_name='联系方式')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱地址')),
                ('city', models.CharField(max_length=16, verbose_name='预约品鉴城市')),
                ('msg', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户留言')),
                ('is_subscribe', models.BooleanField(default=True, verbose_name='是否订阅westbank西岸集团邮件')),
            ],
            options={
                'verbose_name': '预约品鉴',
                'verbose_name_plural': '预约品鉴',
            },
        ),
        migrations.CreateModel(
            name='RDUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('contact_info', models.CharField(max_length=32, verbose_name='联系方式')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱地址')),
                ('is_subscribe', models.BooleanField(default=True, verbose_name='是否订阅westbank西岸集团邮件')),
            ],
            options={
                'verbose_name': '资料下载表单',
                'verbose_name_plural': '资料下载表单',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='资料名称')),
                ('img', models.ImageField(blank=True, max_length=128, null=True, upload_to='resource/image/%Y/%m', verbose_name='资料展示图片')),
                ('download', models.FileField(blank=True, max_length=128, null=True, upload_to='resource/download/%Y/%m', verbose_name='资源文件')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('fav_id', models.IntegerField(default=0, verbose_name='数据id')),
                ('fav_type', models.IntegerField(choices=[(1, '项目'), (2, '课程')], default=1, verbose_name='收藏类型')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
