# Generated by Django 2.1 on 2019-05-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='download',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='resource/download/%Y%m', verbose_name='资源文件'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='img',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to='resource/image/%Y%m', verbose_name='资料展示图片'),
        ),
    ]
