# Generated by Django 2.1 on 2019-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('time_type', models.CharField(choices=[('最新课程', '最新课程'), ('往期课程', '往期课程')], max_length=16, verbose_name='课程时间类型')),
                ('name', models.CharField(max_length=64, verbose_name='课程名称')),
                ('video', models.FileField(blank=True, max_length=128, null=True, upload_to='course/video/%Y%m%d', verbose_name='课程视频')),
                ('img', models.ImageField(blank=True, max_length=128, null=True, upload_to='course/image/%Y%m%d', verbose_name='课程图片')),
                ('audio', models.FileField(blank=True, max_length=128, null=True, upload_to='course/audio/%Y%m%d', verbose_name='课程音频')),
                ('is_on_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_index_recommend', models.BooleanField(default=False, verbose_name='是否首页推荐')),
                ('is_detail_recommend', models.BooleanField(default=False, verbose_name='是否详情页推荐')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
    ]
