# Generated by Django 2.1 on 2019-07-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, help_text='690*360', max_length=128, null=True, upload_to='course/image/%Y%m%d', verbose_name='课程图片'),
        ),
    ]
