# Generated by Django 2.1 on 2019-05-11 22:12

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('image', models.ImageField(max_length=128, upload_to='index/banner/%Y%m%d', verbose_name='轮播图')),
                ('url', models.URLField(max_length=256, verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('is_on_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
                ('project_id', models.IntegerField(verbose_name='项目id')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('logo_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='company/logo/%Y%m%d', verbose_name='公司logo图片')),
                ('video', models.FileField(blank=True, max_length=128, null=True, upload_to='company/video/%Y%m%d', verbose_name='公司视频')),
                ('description', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='课程详情 ')),
                ('bottom', models.TextField(default='{}', verbose_name='公司底部信息')),
            ],
            options={
                'verbose_name': '公司介绍',
                'verbose_name_plural': '公司介绍',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('t_modified', models.DateTimeField(auto_now=True)),
                ('wx_openid', models.CharField(max_length=64, unique=True)),
                ('avatarUrl', models.CharField(blank=True, max_length=256, null=True, verbose_name='微信头像')),
                ('nickName', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信昵称')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女'), (0, '未知')], null=True, verbose_name='性别')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=64, null=True, verbose_name='省份')),
            ],
            options={
                'verbose_name': '用户基本信息',
                'verbose_name_plural': '用户基本信息',
            },
        ),
    ]
