# Generated by Django 2.1 on 2019-05-12 22:32

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='项目id'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='访问地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='公司详情 '),
        ),
    ]
