# Generated by Django 2.1 on 2019-07-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='750*1100', max_length=128, null=True, upload_to='index/banner/%Y%m%d', verbose_name='轮播图'),
        ),
    ]
